=== Churro/CryptoSlice/conf/schema/blacklist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://iaik.tugraz.at/CryptoSlice"
    xmlns="http://iaik.tugraz.at/CryptoSlice"
    elementFormDefault="qualified">
  <xs:element name="blacklist">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="exclude"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="exclude">
    <xs:complexType>
      <xs:attribute name="path-fragment" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Churro/CryptoSlice/conf/blacklist-cryptolibs.xml
<?xml version="1.0" encoding="UTF-8"?>
<blacklist xmlns="http://iaik.tugraz.at/CryptoSlice"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://iaik.tugraz.at/Cryptoslice schema/blacklist.xsd">
  <exclude path-fragment="/amazonaws/" />
  <exclude path-fragment="/android/support/" />
  <exclude path-fragment="/apache/commons/" />
  <exclude path-fragment="/apache/http/" />
  <exclude path-fragment="/apache/james/"/>
  <exclude path-fragment="/apache/poi/"/>
  <exclude path-fragment="/bownzycastle/" />
  <exclude path-fragment="/boye/httpclientandroidlib/" />
  <exclude path-fragment="/ch/qos/logback/" />
  <exclude path-fragment="/com/actionbarsherlock/" />
  <exclude path-fragment="/com/android/volley/" />
  <exclude path-fragment="/com/caverock/androidsvg/" />
  <exclude path-fragment="/COM/claymoresystems/" />
  <exclude path-fragment="/com/coremedia/iso/" />
  <exclude path-fragment="/com/couchbase/lite" />
  <exclude path-fragment="/com/crashlytics/" />
  <exclude path-fragment="/com/fasterxml/jackson/" />
  <exclude path-fragment="/com/googlecode/mp4parser/" />
  <exclude path-fragment="/com/jcraft/jzlib/" />
  <exclude path-fragment="/com/loopj/android/http/" />
  <exclude path-fragment="/com/microblink/" />
  <exclude path-fragment="/com/ning/http/" />
  <exclude path-fragment="/com/qoppa/" />
  <exclude path-fragment="/com/squareup/okhttp/" />
  <exclude path-fragment="/com/squareup/picasso/" />
  <exclude path-fragment="/com/squareup/timessquare/" />
  <exclude path-fragment="/com/sun/mail/" />
  <exclude path-fragment="/com/viewpagerindicator/" />
  <exclude path-fragment="/crashlytics/android/" />
  <exclude path-fragment="/crittercism/android/" />
  <exclude path-fragment="/cryptix/" />
  <exclude path-fragment="/fr/pcsoft/wdjava/" /><!-- prone to provoke endless loops -->
  <exclude path-fragment="/google/android/gms/" />
  <exclude path-fragment="/google/ads/" />
  <exclude path-fragment="/google/api/" />
  <exclude path-fragment="/io/fabric/sdk/" />
  <exclude path-fragment="/jcfis/http/" />
  <exclude path-fragment="/net/hockeyapp/" />
  <exclude path-fragment="/net/sqlcipher/" />
  <exclude path-fragment="/openfeint/" />
  <exclude path-fragment="/org/acra/" />
  <exclude path-fragment="/org/apache/commons/" />
  <exclude path-fragment="/org/apache/cordova/" />
  <exclude path-fragment="/org/apache/harmony/" />
  <exclude path-fragment="/org/apache/james/" />
  <exclude path-fragment="/org/apache/qpid/" />
  <exclude path-fragment="/org/appcelerator/" />
  <exclude path-fragment="/org/bouncycastle/asn1/" />
  <exclude path-fragment="/org/bouncycastle/crypto/" />
  <exclude path-fragment="/org/bouncycastle/jcajce/" />
  <exclude path-fragment="/org/bouncycastle/jce/" />
  <exclude path-fragment="/org/bouncycastle/math/" />
  <exclude path-fragment="/org/bouncycastle/openssl/" />
  <exclude path-fragment="/org/bouncycastle/pqc/" />
  <exclude path-fragment="/org/bouncycastle/util/" />
  <exclude path-fragment="/org/bouncycastle/x509/" />
  <exclude path-fragment="/org/eclipse/jetty/" />
  <exclude path-fragment="/org/jaxen/" />
  <exclude path-fragment="/org/jboss/netty/" />
  <exclude path-fragment="/org/htmlparser/" />
  <exclude path-fragment="/org/mozilla/universalchardet/" />
  <exclude path-fragment="/org/springframework/" />
  <exclude path-fragment="/org/testng/" />
  <exclude path-fragment="/org/tukaani/xz/" />
  <exclude path-fragment="/org/xbill/" />
  <exclude path-fragment="/qoppa/android/" />
  <exclude path-fragment="/senab/photoview/" />
  <exclude path-fragment="/spongycastle/" />
  <exclude path-fragment="/symbouncycastle/" /><!-- used in com.symantec.mobile.idsafe -->
  <exclude path-fragment="/ti/modules/titanium/" />
  <exclude path-fragment="/twitter4j/" />
  <exclude path-fragment="/unity3d/" />
  <exclude path-fragment="/vending/" />
</blacklist>

=== Churro/CryptoSlice/conf/blacklist-adnetworks.xml
<?xml version="1.0" encoding="UTF-8"?>
<blacklist xmlns="http://iaik.tugraz.at/CryptoSlice"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://iaik.tugraz.at/Cryptoslice schema/blacklist.xsd">
	<exclude path-fragment="/admob/" />
	<exclude path-fragment="/google/ads/" />
	<exclude path-fragment="/flurry/" />
	<exclude path-fragment="/analytics/" />
	<exclude path-fragment="/google/analytics/" />
	<exclude path-fragment="/millennialmedia/" />
	<exclude path-fragment="/mobclix/" />
	<exclude path-fragment="/adwhirl/" />
	<exclude path-fragment="/qwapi/" />
	<exclude path-fragment="/youmi/" />
	<exclude path-fragment="/mobfox/" />
	<exclude path-fragment="/zestadz/" />
	<exclude path-fragment="/cauly/" />
	<exclude path-fragment="/inmobi/" />
	<exclude path-fragment="/wooboo/" />
	<exclude path-fragment="/admarvel/" />
	<exclude path-fragment="/smaato/" />
	<exclude path-fragment="/mobclick/" />
	<exclude path-fragment="/nobot/" />
	<exclude path-fragment="/airpush/" />
	<exclude path-fragment="/mdotm/" />
	<exclude path-fragment="/vdopia/" />
	<exclude path-fragment="/wiyun/" />
	<exclude path-fragment="/adhubs/" />
	<exclude path-fragment="/madhouse/" />
	<exclude path-fragment="/pontiflex/" />
	<exclude path-fragment="/innerActive/" />
	<exclude path-fragment="/adview/" />
	<exclude path-fragment="/casee/" />
	<exclude path-fragment="/greystripe/" />
	<exclude path-fragment="/omniture/" />
	<exclude path-fragment="/guohead/" />
	<exclude path-fragment="/mobilead/" />
	<exclude path-fragment="/domob/" />
	<exclude path-fragment="/tapjoy/" />
	<exclude path-fragment="/Adlantis/" />
	<exclude path-fragment="/adagogo/" />
	<exclude path-fragment="/adchina/" />
	<exclude path-fragment="/jumptap/" />
	<exclude path-fragment="/medialets/" />
	<exclude path-fragment="/nowistech/" />
	<exclude path-fragment="/waps/" />
	<exclude path-fragment="/vpon/" />
	<exclude path-fragment="/energysource/" />
	<exclude path-fragment="/iconosys/" />
	<exclude path-fragment="/adwo/" />
	<exclude path-fragment="/sktelecom/" />
	<exclude path-fragment="/uplusad/" />
	<exclude path-fragment="/smartadserver/" />
	<exclude path-fragment="/airad/" />
	<exclude path-fragment="/emome/" />
	<exclude path-fragment="/mopub/" />
	<exclude path-fragment="/adfonic/" />
	<exclude path-fragment="/vdroid/" />
	<exclude path-fragment="/transpera/" />
	<exclude path-fragment="/mobgold/" />
	<exclude path-fragment="/mobus/" />
	<exclude path-fragment="/hutuchong/" />
	<exclude path-fragment="/mads/" />
	<exclude path-fragment="/everbadge/" />
	<exclude path-fragment="/zetacube/" />
	<exclude path-fragment="/smartad/" />
	<exclude path-fragment="/adlib_android/" />
	<exclude path-fragment="/trickersticks/" />
	<exclude path-fragment="/ccmedia/" />
	<exclude path-fragment="/sosceo/" />
	<exclude path-fragment="/Mojiva/" />
	<exclude path-fragment="/admogo/" />
	<exclude path-fragment="/nexage/" />
	<exclude path-fragment="/rhythmnewmedia/" />
	<exclude path-fragment="/mediba/" />
	<exclude path-fragment="/madvertise/" />
	<exclude path-fragment="/qriously/" />
	<exclude path-fragment="/zumobi/" />
	<exclude path-fragment="/netmite/" />
	<exclude path-fragment="/imapp/" />
	<exclude path-fragment="/yicha/" />
	<exclude path-fragment="/oneriot/" />
	<exclude path-fragment="/aduru/" />
	<exclude path-fragment="/admoda/" />
	<exclude path-fragment="/imobile/" />
	<exclude path-fragment="/moblico/" />
	<exclude path-fragment="/linkshare/" />
	<exclude path-fragment="/ignitevision/" />
	<exclude path-fragment="/fractalist/" />
	<exclude path-fragment="/plankton/" />
	<exclude path-fragment="/cellitads/" />
	<exclude path-fragment="/appmedia/" />
	<exclude path-fragment="/glam/" />
	<exclude path-fragment="/adtutu/" />
	<exclude path-fragment="/adfox/" />
	<exclude path-fragment="/netad/" />
	<exclude path-fragment="/freewheel/" />
	<exclude path-fragment="/adinside/" />
	<exclude path-fragment="/taobao/" />
	<exclude path-fragment="/amaze/" />
	<exclude path-fragment="/admozi/" />
	<exclude path-fragment="/wqmobile/" />
	<exclude path-fragment="/ubermind/" />
	<exclude path-fragment="/innoace/" />
	<exclude path-fragment="/adyx/" />
</blacklist>
